import pandas as pd
import numpy as np

def load_df():
    df = pd.read_csv('complete_df.csv')
    df.pop('Unnamed: 0')
    df.drop(0, inplace=True)
    df.rename(columns={'nz_covers_att':'nz_convers_att', 'opp_covers_att':'opp_convers_att'}, inplace=True)
    return df

def correct_dtypes(df):
    # int dtypes
    df[['match_id',
    'nz_half_points',
    'opp_half_points',
    'nz_final_score',
    'opp_final_score',
    'nz_tries',
    'opp_tries',
    'nz_convers_made',
    'nz_convers_att',
    'opp_convers_made',
    'opp_convers_att',
    'nz_pen_made',
    'nz_pen_att',
    'opp_pen_made',
    'opp_pen_att',
    'nz_drop_goal_made',
    'nz_drop_goal_miss',
    'opp_drop_goal_made',
    'opp_drop_goal_miss',
    'nz_kicks_from_hand',
    'opp_kicks_from_hand',
    'nz_passes',
    'opp_passes',
    'nz_runs',
    'opp_runs',
    'nz_metres_run_w_ball',
    'opp_metres_run_w_ball',
    'nz_clean_breaks',
    'opp_clean_breaks',
    'nz_defenders_beat',
    'opp_defenders_beat',
    'nz_offloads',
    'opp_offloads',
    'nz_rucks_total',
    'nz_rucks_won',
    'nz_rucks_lost',
    'opp_rucks_total',
    'opp_rucks_won',
    'opp_rucks_lost',
    'nz_maul_total',
    'nz_maul_won',
    'nz_maul_lost',
    'opp_maul_total',
    'opp_maul_won',
    'opp_maul_lost',
    'nz_turnovers_conceded',
    'opp_turnovers_conceded',
    'nz_tackles_made',
    'nz_tackles_miss',
    'nz_tackles_total',
    'opp_tackles_made',
    'opp_tackles_miss',
    'opp_tackles_total',
    'nz_scrums_own_won',
    'nz_scrums_own_lost',
    'nz_scrums_own_total',
    'opp_scrums_own_won',
    'opp_scrums_own_lost',
    'opp_scrums_own_total',
    'nz_lineout_own_won',
    'nz_lineout_own_lost',
    'nz_lineout_own_total',
    'opp_lineout_own_won',
    'opp_lineout_own_lost',
    'opp_lineout_own_total',
    'nz_pen_conceded',
    'nz_freekick_conceded',
    'opp_pen_conceded',
    'opp_freekick_conceded',
    'nz_yellow_card',
    'nz_red_card',
    'opp_yellow_card',
    'opp_red_card']] = df[['match_id',
    'nz_half_points',
    'opp_half_points',
    'nz_final_score',
    'opp_final_score',
    'nz_tries',
    'opp_tries',
    'nz_convers_made',
    'nz_convers_att',
    'opp_convers_made',
    'opp_convers_att',
    'nz_pen_made',
    'nz_pen_att',
    'opp_pen_made',
    'opp_pen_att',
    'nz_drop_goal_made',
    'nz_drop_goal_miss',
    'opp_drop_goal_made',
    'opp_drop_goal_miss',
    'nz_kicks_from_hand',
    'opp_kicks_from_hand',
    'nz_passes',
    'opp_passes',
    'nz_runs',
    'opp_runs',
    'nz_metres_run_w_ball',
    'opp_metres_run_w_ball',
    'nz_clean_breaks',
    'opp_clean_breaks',
    'nz_defenders_beat',
    'opp_defenders_beat',
    'nz_offloads',
    'opp_offloads',
    'nz_rucks_total',
    'nz_rucks_won',
    'nz_rucks_lost',
    'opp_rucks_total',
    'opp_rucks_won',
    'opp_rucks_lost',
    'nz_maul_total',
    'nz_maul_won',
    'nz_maul_lost',
    'opp_maul_total',
    'opp_maul_won',
    'opp_maul_lost',
    'nz_turnovers_conceded',
    'opp_turnovers_conceded',
    'nz_tackles_made',
    'nz_tackles_miss',
    'nz_tackles_total',
    'opp_tackles_made',
    'opp_tackles_miss',
    'opp_tackles_total',
    'nz_scrums_own_won',
    'nz_scrums_own_lost',
    'nz_scrums_own_total',
    'opp_scrums_own_won',
    'opp_scrums_own_lost',
    'opp_scrums_own_total',
    'nz_lineout_own_won',
    'nz_lineout_own_lost',
    'nz_lineout_own_total',
    'opp_lineout_own_won',
    'opp_lineout_own_lost',
    'opp_lineout_own_total',
    'nz_pen_conceded',
    'nz_freekick_conceded',
    'opp_pen_conceded',
    'opp_freekick_conceded',
    'nz_yellow_card',
    'nz_red_card',
    'opp_yellow_card',
    'opp_red_card']].apply(lambda x: int(x) if type(x) == float)


    # return df
    # datetime dtypes
    # df['date'] = pd.to_datetime(df['date'], infer_datetime_format=True)
    # df[['local_time', 'gmt_time']] = df[['local_time', 'gmt_time']].dt.time
    return df

def categorize(df):
    pass


if __name__ == '__main__':
    df_raw = load_df()
    df = correct_dtypes(df_raw)



# ['match_id',
#  'home_team',
#  'away_team',
#  'tournament',
#  'location',
#  'date',
#  'local_time',
#  'gmt_time',
#  'nz_half_points',
#  'opp_half_points',
#  'nz_final_score',
#  'opp_final_score',
#  'result',
#  'nz_tries',
#  'opp_tries',
#  'nz_convers_made',
#  'nz_covers_att',
#  'opp_convers_made',
#  'opp_covers_att',
#  'nz_pen_made',
#  'nz_pen_att',
#  'opp_pen_made',
#  'opp_pen_att',
#  'nz_kick_goal_perc',
#  'opp_kick_goal_perc',
#  'nz_drop_goal_made',
#  'nz_drop_goal_miss',
#  'opp_drop_goal_made',
#  'opp_drop_goal_miss',
#  'nz_kicks_from_hand',
#  'opp_kicks_from_hand',
#  'nz_passes',
#  'opp_passes',
#  'nz_runs',
#  'opp_runs',
#  'nz_metres_run_w_ball',
#  'opp_metres_run_w_ball',
#  'nz_possession_1h',
#  'nz_possession_2h',
#  'nz_possession_total',
#  'opp_possession_1h',
#  'opp_possession_2h',
#  'opp_possession_total',
#  'nz_territory_1h',
#  'nz_territory_2h',
#  'nz_territory_total',
#  'opp_territory_1h',
#  'opp_territory_2h',
#  'opp_territory_total',
#  'nz_clean_breaks',
#  'opp_clean_breaks',
#  'nz_defenders_beat',
#  'opp_defenders_beat',
 # 'nz_offloads',
 # 'opp_offloads',
 # 'nz_rucks_total',
 # 'nz_rucks_won',
 # 'nz_rucks_lost',
#  'nz_rucks_perc',
 # 'opp_rucks_total',
 # 'opp_rucks_won',
 # 'opp_rucks_lost',
#  'opp_rucks_perc',
 # 'nz_maul_total',
 # 'nz_maul_won',
 # 'nz_maul_lost',
#  'nz_maul_perc',
 # 'opp_maul_total',
 # 'opp_maul_won',
 # 'opp_maul_lost',
#  'opp_maul_perc',
 # 'nz_turnovers_conceded',
 # 'opp_turnovers_conceded',
 # 'nz_tackles_made',
 # 'nz_tackles_miss',
 # 'nz_tackles_total',
#  'nz_tackles_perc',
 # 'opp_tackles_made',
 # 'opp_tackles_miss',
 # 'opp_tackles_total',
#  'opp_tackles_perc',
 # 'nz_scrums_own_won',
 # 'nz_scrums_own_lost',
 # 'nz_scrums_own_total',
#  'nz_scrums_own_perc',
 # 'opp_scrums_own_won',
 # 'opp_scrums_own_lost',
 # 'opp_scrums_own_total',
#  'opp_scrums_own_perc',
 # 'nz_lineout_own_won',
 # 'nz_lineout_own_lost',
 # 'nz_lineout_own_total',
#  'nz_lineout_own_perc',
 # 'opp_lineout_own_won',
 # 'opp_lineout_own_lost',
 # 'opp_lineout_own_total',
#  'opp_lineout_own_perc',
 # 'nz_pen_conceded',
 # 'nz_freekick_conceded',
 # 'opp_pen_conceded',
 # 'opp_freekick_conceded',
 # 'nz_yellow_card',
 # 'nz_red_card',
 # 'opp_yellow_card',
 # 'opp_red_card']
